# .pre-commit-config.yaml

# pylint has issues with python 3.9
#default_language_version:
#    python: python3.8

repos:

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
       - id: flake8

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.0
    hooks:
       - id: darglint

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.4
    hooks:
       - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
       - id: mypy
