name: cf_tools_test
channels:
  - conda-forge
dependencies:
  - pytest-cov
  - pytest
  - netcdf4
  - dask
  - imageio
  - matplotlib
  - xarray
  - cf_xarray
  - xgcm
  - gsw
  - xoak
  - pys2index
  - pooch
  - pip
